# Generated by Django 3.1.3 on 2022-05-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
