# Generated by Django 3.1.3 on 2022-05-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_auto_20220505_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='hacker.gif', null=True, upload_to='profile_pics'),
        ),
    ]
